package org.devs.crm.model;

import lombok.*;

import java.math.BigDecimal;
import java.time.LocalTime;

/**
 * <p>Entity course</p>
 *
 * <b>States:</b>
 * <ul>
 *     <li>id - should be generated by database or orm</li>
 *     <li>name - should not be null</li>
 *     <li>subject - should not be null or blank</li>
 *     <li>courseDurationInMonth - should not be null and less than or equal to zero </li>
 *     <li>lessonDuration - should not be null </li>
 *     <li>coursePrice - should not be null or less than zero</li>
 * </ul>
 */

@Getter
@Setter
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    private Long id;
    private String name;
    private String subject;
    private Integer courseDurationInMonth;
    private LocalTime lessonDuration;
    private BigDecimal coursePrice;

}


