package org.devs.crm.model;

import lombok.*;

import java.math.BigDecimal;

/**
 * <p>Entity mentor</p>
 *
 * <b>States:</b>
 * <ul>
 *     <li>id - should be generated by database or orm</li>
 *     <li>firstName - should not be null or blank</li>
 *     <li>lastName - should not be null or blank </li>
 *     <li>patronymic - should be null or null</li>
 *     <li>email - should not be null or blank</li>
 *     <li>phoneNumber - should not be null</li>
 *     <li>salary - should not be null</li>
 * </ul>
 */

@Getter
@Setter
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Mentor {

    private Long id;
    private String firstName;
    private String lastName;
    private String patronymic;
    private String email;
    private String phoneNumber;
    private BigDecimal salary;

}
