package org.devs.crm.entity;

import lombok.*;

import java.time.LocalDate;
import java.util.List;

/**
 * <p>Entity group</p>
 *
 * <b>States:</b>
 * <ul>
 *     <li>id - should be generated by database or orm</li>
 *     <li>groupName - should not be null or blank</li>
 *     <li>course - should not be null</li>
 *     <li>students - should not be null</li>
 *     <li>mentors - should not be null</li>
 *     <li>startDate - should not be null</li>
 * </ul>
 */

@Getter
@Setter
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Group {

    private Long id;
    private String groupName;
    private Course course;
    private List<Student> students;
    private List<Mentor> mentors;
    private LocalDate startDate;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Group group = (Group) o;

        return getId() != null ? getId().equals(group.getId()) : group.getId() == null;
    }

    @Override
    public int hashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }
}