package org.devs.crm.entity;

import lombok.*;

import java.math.BigDecimal;

/**
 * <p>Entity mentor</p>
 *
 * <b>States:</b>
 * <ul>
 *     <li>id - should be generated by database or orm</li>
 *     <li>firstName - should not be null or blank</li>
 *     <li>lastName - should not be null or blank </li>
 *     <li>patronymic - should be null or null</li>
 *     <li>email - should not be null or blank</li>
 *     <li>phoneNumber - should not be null</li>
 *     <li>salary - should not be null</li>
 * </ul>
 */

@Getter
@Setter
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Mentor {

    private Long id;
    private String firstName;
    private String lastName;
    private String patronymic;
    private String email;
    private String phoneNumber;
    private BigDecimal salary;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Mentor mentor = (Mentor) o;

        return getId() != null ? getId().equals(mentor.getId()) : mentor.getId() == null;
    }

    @Override
    public int hashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }

}
